### ISSUE TITLE
Everynet downlink response LORA=1 parameter

### ISSUE THREAD

**Issue by rfsales** [php-mqtt/client#107]
There is any way to use LORA=1 on php-mqtt/client?
My need's to send command to end device by downlink_response

lora=1 - enables connection to receive not only application data, but also all MAC commands generated by network server. MAC commands will be included into uplink and downlink messages. Default value is 0.

https://ns.docs.everynet.io/data-api/connection.html

**Comment by Namoshek** [comment]
Not sure what this has to do with MQTT, the linked documentation talks about WebSockets?

**Comment by rfsales** [comment]
I thought there was an equivalent command.

Today I found out that it was the ADR was disturbing the Downlink.
