### ISSUE TITLE
The configured broker responded with unauthorized

### ISSUE THREAD

**Issue by Bagunda** [php-mqtt/client#118]
I check in console ip-address, login, password. It work.
But php page print error:

```php
Fatal error: Uncaught PhpMqtt\Client\Exceptions\ConnectingToBrokerFailedException: [6] Establishing a connection to the MQTT broker failed: The configured broker responded with unauthorized. in /var/www/html/vendor/php-mqtt/client/src/MessageProcessors/Mqtt31MessageProcessor.php:252 Stack trace: #0 /var/www/html/vendor/php-mqtt/client/src/MqttClient.php(377): PhpMqtt\Client\MessageProcessors\Mqtt31MessageProcessor->handleConnectAcknowledgement() #1 /var/www/html/vendor/php-mqtt/client/src/MqttClient.php(158): PhpMqtt\Client\MqttClient->performConnectionHandshake() #2 /var/www/html/vendor/php-mqtt/client/src/MqttClient.php(144): PhpMqtt\Client\MqttClient->connectInternal() #3 /var/www/html/sonos_webhook.php(50): PhpMqtt\Client\MqttClient->connect() #4 {main} thrown in /var/www/html/vendor/php-mqtt/client/src/MessageProcessors/Mqtt31MessageProcessor.php on line 252
```

```php
require('vendor/autoload.php');

use \PhpMqtt\Client\MqttClient;
use \PhpMqtt\Client\ConnectionSettings;

$server   = '192.168.84.66';
$port     = 1883;
$clientId = 'sonos_webhook.php';
$username = 'user1';
$password = "pass1";

$connectionSettings  = new ConnectionSettings();
$connectionSettings
  ->setUsername($username)
  ->setPassword($password);

$mqtt = new \PhpMqtt\Client\MqttClient($server, $port, $clientId);
$mqtt->connect($connectionSettings, true);
$mqtt->publish('php-mqtt/client/test', 'Hello World!', 0);
$mqtt->disconnect();
```

**Comment by Namoshek** [comment]
What type of broker are you using? I suspect that you are using Home Assistant with the Mosquitto plugin, which apparently seems to behave strangely as already discussed in #105. I've no solution for this as I'm unable to reproduce the issue.

**Comment by Bagunda** [comment]
Home Assistant with the Mosquitto plugin just installed

**Comment by squpshift** [comment]
I am having the same experience with hivemq managed broker

**Comment by Namoshek** [comment]
@squpshift This is most likely a different issue. Please create a new issue and provide details regarding your setup.

**Comment by gromqk** [comment]
> I check in console ip-address, login, password. It work. But php page print error:
> 
> ```
> Fatal error: Uncaught PhpMqtt\Client\Exceptions\ConnectingToBrokerFailedException: [6] Establishing a connection to the MQTT broker failed: The configured broker responded with unauthorized. in /var/www/html/vendor/php-mqtt/client/src/MessageProcessors/Mqtt31MessageProcessor.php:252 Stack trace: #0 /var/www/html/vendor/php-mqtt/client/src/MqttClient.php(377): PhpMqtt\Client\MessageProcessors\Mqtt31MessageProcessor->handleConnectAcknowledgement() #1 /var/www/html/vendor/php-mqtt/client/src/MqttClient.php(158): PhpMqtt\Client\MqttClient->performConnectionHandshake() #2 /var/www/html/vendor/php-mqtt/client/src/MqttClient.php(144): PhpMqtt\Client\MqttClient->connectInternal() #3 /var/www/html/sonos_webhook.php(50): PhpMqtt\Client\MqttClient->connect() #4 {main} thrown in /var/www/html/vendor/php-mqtt/client/src/MessageProcessors/Mqtt31MessageProcessor.php on line 252
> ```
> 
> ```
> require('vendor/autoload.php');
> 
> use \PhpMqtt\Client\MqttClient;
> use \PhpMqtt\Client\ConnectionSettings;
> 
> $server   = '192.168.84.66';
> $port     = 1883;
> $clientId = 'sonos_webhook.php';
> $username = 'user1';
> $password = "pass1";
> 
> $connectionSettings  = new ConnectionSettings();
> $connectionSettings
>   ->setUsername($username)
>   ->setPassword($password);
> 
> $mqtt = new \PhpMqtt\Client\MqttClient($server, $port, $clientId);
> $mqtt->connect($connectionSettings, true);
> $mqtt->publish('php-mqtt/client/test', 'Hello World!', 0);
> $mqtt->disconnect();
> ```
Строки
```
$connectionSettings
  ->setUsername($username)
  ->setPassword($password);
```
  не меняют сам объект, а возвращают другой.
  т.е. можно сделать например так:
```
$connectionSettingsObj  = new ConnectionSettings();
$connectionSettings = $connectionSettingsObj
  ->setUsername($username)
  ->setPassword($password);
```
