### ISSUE TITLE
tls 1.2 not supported?

### ISSUE THREAD

**Issue by Netbulae** [php-mqtt/client#120]
Currently we have implemented the php-mqtt client into our application.
We need to have the connection encrypted as the broker is not hosted on localhost and we need to use client certificates.
Have enabled alle the tls connection parameters and added the proper certificates

But I keep getting a ssl handshake error in mosquitto, the current mosquitto only supports tls v1.2 and v1.3

1656494608: OpenSSL Error[0]: error:140780E5:SSL routines:ssl23_read:ssl handshake failure
1656494614: OpenSSL Error[0]: error:140780E5:SSL routines:ssl23_read:ssl handshake failure
1656495013: OpenSSL Error[0]: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
1656495031: OpenSSL Error[0]: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol

Is tls v1.2 supported as I see in the connection string SSL23. I've looked in the code and I cannot find where the ssl/tls protocol selection comes from?

**Comment by Namoshek** [comment]
Sounds like your client platform does not support this TLS versions?

**Comment by Namoshek** [comment]
Currently, no protocol whitelisting is implemented and all TLS protocols are supported, as long as the operating system supports them:

https://github.com/php-mqtt/client/blob/d54381306e68baf7c2c089392c0c6d1d06e278c6/src/MqttClient.php#L263

**Comment by Netbulae** [comment]
Have been testing with openssl on the host without any problems as on dev we have a localhost setup.
I'm currently suspecting php 7.4, we need to deprecate a library we use to get to 8+

Bug #79501 | TLS connections freezing on 7.4 (all versions after 7.3.17)
https://bugs.php.net/bug.php?id=79501

Will test in a different environment in the morning, thanx for the response!

**Comment by Namoshek** [comment]
@Netbulae were you able to test a different configuration already?

**Comment by Namoshek** [comment]
Closed due to inactivity.
