### ISSUE TITLE
Subscribers get congested

### ISSUE THREAD

**Issue by jage0435** [php-mqtt/client#122]
I have 200 more devices and my laravel service will recieve more than 15 messages per second. Recently I found that subscriptions accumulate messages, causing data delays to become more and more serious. My question is the data arrived event is synchronous? 
（The average data processing time is about 1.2 seconds.）

**Comment by Namoshek** [comment]
If you are not implementing any async logic yourself, the whole client works synchronously - that's right. I therefore advise you to use an intermediary queue to schedule the processing, which can then be done by (multiple) other processes. In other words, your `subscribe()` callbacks should push the received message (incl. topic and what other infos you need) to a queue, which is processed by a bunch of worker processes - to parallelize the work.

**Comment by jage0435** [comment]
thanks for your answer, this repository is amazing! :)

**Comment by Namoshek** [comment]
@jage0435 Actually, there is another option: shared subscriptions. Maybe, when your broker supports it, you can run multiple workers with an MQTT subscription in parallel. See #75 for more details. This would distribute incoming messages on multiple processes.

**Comment by jage0435** [comment]
This is what I want! but i found broker will keep old shared subscribe when i restart mqtt client, so my client message will less and less until i restart broker. When i restart my client, broker will receive willMessage, so i'm sure connection not kept. i'm also used MQTTX client desktop app to confirm if it was the broker's problem, but app works fine.

this is my setting below:
  $this->mqtt = new MqttClient(config('mqtt.server'), config('mqtt.port'));
  $connectionSettings = (new ConnectionSettings())
      ->setUsername(config('mqtt.username'))
      ->setPassword(config('mqtt.password'))
      ->setConnectTimeout(5)
      ->setLastWillTopic("willTest")
      ->setLastWillMessage("willMsgTest")
      ->setUseTls(config('mqtt.tls'));
  $this->mqtt->connect($connectionSettings);

**Comment by Namoshek** [comment]
What broker are you using?

**Comment by jage0435** [comment]
@Namoshek  mosquitto mqtt broker - version :2.0.11

**Comment by jage0435** [comment]
I really appreciate your prompt reply, all my problems have been solved. Thank you!
