### ISSUE TITLE
Error in readme

### ISSUE THREAD

**Issue by geri777** [php-mqtt/client#132]
You are writing the following sample script in the readme:
$mqtt = new \PhpMqtt\Client\MqttClient

But it should be MQTTClient, not MqttClient

Many thanks, Geri

**Comment by Namoshek** [comment]
The class has been renamed from `MQTTClient` to `MqttClient` in `v1.0.0`. It looks like you are using an old version, please check your `composer.lock` for the installed version. If this does not show an old version, uninstall and reinstall the client - maybe composer has troubles renaming the files on some operating systems.

**Comment by geri777** [comment]
Thank you for your fast reply. I am so sorry, I had a very old version in my composer.json and thought I had added I newly to my project.
