### ISSUE TITLE
TLS error in a connection

### ISSUE THREAD

**Issue by MrXBear** [php-mqtt/client#142]
I can connect a server by MQTTX (a desktop client) successfully.
![gui](https://user-images.githubusercontent.com/47053993/213956452-7431f513-0f3a-405b-9ecf-5410ecafae58.png)

but when I connecting to the same server with same config, I got an error

Here is my code

```php
$server   = 'server';
$port     = 1883;
$clientId = 'clientId';

$mqtt = new MqttClient($server, $port, $clientId, MqttClient::MQTT_3_1_1, null);

$username = 'username';
$password = 'password';

$setting = (new ConnectionSettings())
    ->setLastWillQualityOfService(0)
    ->setRetainLastWill(false)
    ->setUsername($username)
    ->setPassword($password)
    ->setUseTls(true)
    ->setTlsSelfSignedAllowed(true)
    ->setTlsClientCertificateFile("MQ_Certificate.pem")
;

$mqtt->connect($setting, true);
```

then it shows the error :
`[2000] Establishing a connection to the MQTT broker failed: TLS error [UNKNOWN:2]: stream_socket_enable_crypto(): Unable to set private key file 'D:\MQ_Certificate.pem'`

I wonder that did I do something wrong or miss some config in above codes.
Thanks a lot. ❤

**Comment by Namoshek** [comment]
I'm not very familiar with PHP under Windows, but to me it looks like the `setTlsClientCertificateFile("MQ_Certificate.pem")` is misinterpreted and the `MQ_Certificate.pem` is not located at `D:\MQ_Certificate.pem`. You might be able to work around this issue by providing an absolute path or by prefixing the path with `__DIR__`:
```php
->setTlsClientCertificateFile(__DIR__.'MQ_Certificate.pem')
```

**Comment by MrXBear** [comment]
> I'm not very familiar with PHP under Windows, but to me it looks like the `setTlsClientCertificateFile("MQ_Certificate.pem")` is misinterpreted and the `MQ_Certificate.pem` is not located at `D:\MQ_Certificate.pem`. You might be able to work around this issue by providing an absolute path or by prefixing the path with `__DIR__`:
> 
> ```
> ->setTlsClientCertificateFile(__DIR__.'/MQ_Certificate.pem')
> ```

This PHP script (`Test.php`) and `MQ_Certificate.pem` are in the same directoy, 
so we can use relative path simply.

I have tested the "absolute path", and got the same error again.
I tested the same code in Linux (Ubuntu 22.04), and it still throwed the same error. 😂

I also tested a nonexistence file, like `->setTlsClientCertificateFile('NotExistence.pem')`
got error `The client certificate file setting must contain the path to a regular file.`
in function `PhpMqtt\Client\MqttClient->ensureConnectionSettingsAreValid()`

**Comment by Namoshek** [comment]
Hm, interesting. According to [this question on StackOverflow](https://stackoverflow.com/questions/26890378/warning-stream-socket-client-unable-to-set-private-key-file), the error could indicate that the PEM-file is malformed. Another option is you are missing the passphrase for your private key, if it has one.

**Comment by MrXBear** [comment]
> Hm, interesting. According to [this question on StackOverflow](https://stackoverflow.com/questions/26890378/warning-stream-socket-client-unable-to-set-private-key-file), the error could indicate that the PEM-file is malformed. Another option is you are missing the passphrase for your private key, if it has one.

It turned out that I used a wrong function.
I should use `->setTlsCertificateAuthorityFile('some.pem')` instead of `->setTlsClientCertificateFile('some.pem')`.

I tried the right function, then I got a new error:
`[2000] Establishing a connection to the MQTT broker failed: TLS error [UNKNOWN:2]: stream_socket_enable_crypto(): Peer certificate CN='A_NAME' did not match expected CN='AN_IP_ADDRESS'`

Because of trusting that server, I should have used the function `->setTlsVerifyPeerName(false)` to ignore the warning/error.
But I didn't do this in the previous attempts.  (One mistake after another. 😰)

So, the correct config code like this:
```php
$setting = (new ConnectionSettings())
    ->setUsername($username)
    ->setPassword($password)
    ->setUseTls(true)
    ->setTlsCertificateAuthorityFile("MQ_Certificate.pem")    // CertAuth, not ClientCert
    ->setTlsVerifyPeerName(false);    // ignore that warning
```
I tried the code above, and it worked successfully ~
The problem solved.

Thank you all the same. ❤
Please ignore my mistakes in English.
Have a good day & Happy Chinese New Year ~

**Comment by Namoshek** [comment]
Ah, I see. Since a `.pem` file can be used for both types of certificates, that really was not obvious with the given details. :+1:

What I don't understand is why you connect to your broker with an IP address instead of the CNAME for which the certificate is issued? If you'd use the CNAME (`A_NAME` in your example) to connect to the broker, `setTlsVerifyPeerName(false)` should not be necessary. Using this option reduces security.

**Comment by MrXBear** [comment]
> Ah, I see. Since a `.pem` file can be used for both types of certificates, that really was not obvious with the given details. 👍
> 
> What I don't understand is why you connect to your broker with an IP address instead of the CNAME for which the certificate is issued? If you'd use the CNAME (`A_NAME` in your example) to connect to the broker, `setTlsVerifyPeerName(false)` should not be necessary. Using this option reduces security.

Because that CNAME is just the name of the MQ platform (`OneNET MQ`), not a legal, accessable host.
And the platform only provided the IP, the port, and the `.pem` file.

In the other hand, my project is still in the testing stage.
So, it is acceptable to lose some security.
I won't do that in the production environment. 🔐

**Comment by Namoshek** [comment]
Alright, then I consider this issue resolved. 👍
