### ISSUE TITLE
Sending data over the socket to the broker failed.

### ISSUE THREAD

**Issue by samo9789** [php-mqtt/client#150]
Hi (again)

Still on the project where we have several MQTT devices, we randomly (on all devices, not only 4G ones) get this error

MQTT [{host}:{port}] [{clientId}] Sending data over the socket to the broker failed.

Can you tell me more about the root cause, in your library, for such an error ?

thank you

**Comment by Namoshek** [comment]
This error is raised for all types of communication errors, but most likely if the socket has been closed or is in an unusable state for some reason. Some possible reasons are:
- a socket timeout (i.e. timeout on TCP level or network changed) occurred
- a timeout on protocol level occurred, leading to a disconnect by the broker (i.e. no keep alive ping sent by client)
- a transmission error occurs (this is extremely rare thanks to TCP checksum)
- the client has high latency or high package loss (quite likely with mobile networks)
- the client sends too much data (in a short period of time), exceeding the buffer size of the broker and the broker closes the connection (rather unlikely with mobile networks)

In general, it is extremely hard to tell what the exact reason is. PHP doesn't really give a reason, it simply tells us it could not read from or write to the socket. The error messages of this library are not intentionally unhelpful, we simply don't have more details at our disposal.

**Comment by Namoshek** [comment]
Closed due to inactivity.
