### ISSUE TITLE
Writing large string error

### ISSUE THREAD

**Issue by giuseppedevito** [php-mqtt/client#155]
I think there is a bug at line 1150 of MqttClient class:

https://github.com/php-mqtt/client/blob/0847abe2b9129833dc1c44f0fc1df3b0fb6157e2/src/MqttClient.php#L1141-L1171

This will result in `DataTransferException` event with messages over 100 KB (MQTT has a maximum allowed message size of 256 MB).

I solved the issue adding the method:
```php
protected function writeChunks($fp, $string) {
    $fwrite = 0;
    for ($written = 0; $written < strlen($string); $written += $fwrite) {
        $fwrite = @fwrite($fp, substr($string, $written));
        if ($fwrite === false) {
            return $written;
        }
    }
    return $written;
}
```

and changing line 1150 to:
```php
$result = $this->writeChunks($this->socket, $data);
```

With this update your code is working fine.

**Comment by Namoshek** [comment]
A detailed analysis and a possible solution regarding this issue can be found in #133.

**Comment by giuseppedevito** [comment]
Tanks for your fast reply @Namoshek  ... #133  closes this issue.
