### ISSUE TITLE
Run the script when there is a new message

### ISSUE THREAD

**Issue by Jamedeveloper** [php-mqtt/client#157]
Hi, 
First, thank you very much for your complete library.
I am new to MQTT and I apologize if my question is a beginner.

I am working on a project where a Nodemcu module sends data from a number of sensors to a server. (sent every second)
To receive this information, the php code I wrote using your library must be running to receive and process the information.

Now I want to make it so that if a new message comes, the script related to the processing will be executed.

**Comment by Namoshek** [comment]
When using MQTT to subscribe to topics, the subscriber commonly runs all the time. This means that running subscriptions inside a web request is not going to work. Instead, you should run the script permanently as daemon on the server. A good way to achieve this is via a service manager or init process like systemd or supervisord.

**Comment by Jamedeveloper** [comment]
Thank you for your reply.

I have two questions.

1- When the publisher sends the message and the retain flag is set to one, the subscriber always returns the last message sent. I want it to return nothing if there are no new and unread messages.

2- Is there a program that returns all of messages as an array if several messages have been published and have not been read due to the unavailability of subscriber messages?

If possible, please give an example of the codes.

**Comment by Namoshek** [comment]
> 1- When the publisher sends the message and the retain flag is set to one, the subscriber always returns the last message sent. I want it to return nothing if there are no new and unread messages.

That's not possible. An MQTT broker doesn't remember which subscriber received which message. If you need such functionality, MQTT is the wrong protocol and AMQP could be a better fit.

> 2- Is there a program that returns all of messages as an array if several messages have been published and have not been read due to the unavailability of subscriber messages?

No, messages are published one-by-one by the broker. Since you don't know on the client-side whether a message sent by the broker is _the last message "for now"_, you can't easily aggregate them.
