### ISSUE TITLE
Transferring data over socket failed

### ISSUE THREAD

**Issue by DancingDream** [php-mqtt/client#159]
hi, I have a problem. An error occurred when I pushed a new message after I subscribed to the topic circularly. The server can receive new messages.
![1681715358](https://user-images.githubusercontent.com/72026740/232410610-6982b530-e6a8-48b0-8973-a80413168a40.png)

**Comment by Namoshek** [comment]
Please provide the code you are using.

**Comment by DancingDream** [comment]
![image](https://user-images.githubusercontent.com/72026740/232641062-9a572140-b2c8-4127-8cce-5caee6ba2422.png)

**Comment by Namoshek** [comment]
That's only half of the code, the connect part is missing. It is also a potential issue that you are using globals and sleep in your code. Depending on the timeouts you used for the connection, the broker may simply have disconnected you.

Regarding your logic, there is an issue as well:
Calling `$mqtt->subscribe(...)` will only issue the subscription request, but it is not a working subscription just yet. You need to call `$mqtt->loop()` for it to become a valid subscription because the MQTT broker has to acknowledge it. This may need some time (commonly a few milliseconds, depending on the connection). Whether you can publish a message to yourself, depends on the broker - some MQTT brokers do not broadcast messages to the sender if they run subscriptions as well.

**Comment by Egregius** [comment]
Is using globals and sleep an issue then? I'm also seeing the same error from time to time.

This is my code:
`#!/usr/bin/php
<?php
declare(strict_types=1);
$user='MQTT';
require '/var/www/vendor/autoload.php';
require '/var/www/html/secure/functions.php';
lg('Starting MQTT loop...');
use PhpMqtt\Client\MqttClient;

$client = new MqttClient('127.0.0.1', 1883, 'pass4mqtt', MqttClient::MQTT_3_1, null, null);
$client->connect(null, true);
$client->subscribe('#', function (string $topic, string $message, bool $retained) use ($client) {
	$user='MQTT';
	$time=time();
	$topic=explode('/', $topic);
	if ($topic[0]=='domoticz') {
		if ($topic[1]=='out') {
			global $dbname,$dbuser,$dbpass,$user,$domoticzurl;
			$d=fetchdata();
			dag();
			$message=json_decode($message, true);
			$device=$message['name'];
			$status=$message['svalue1'];
			if (file_exists('/var/www/html/secure/pass2php/'.$device.'.php')) {
				if ($message['dtype']=='Light/Switch') {
					if ($message['switchType']=='Dimmer') {
						if ($message['nvalue']==0) $status=0;
						else $status=$message['svalue1'];
					} elseif ($message['switchType']=='Blinds Percentage') {
						if ($message['nvalue']==0) $status=0;
						elseif ($message['nvalue']==1) $status=100;
						else $status=$message['svalue1'];
					} elseif ($message['switchType']=='Contact') {
						if ($message['nvalue']==0) $status='Closed';
						elseif ($message['nvalue']==1) $status='Open';
					} elseif ($message['switchType']=='Door Contact') {
						if ($device=='achterdeur') {
							if ($message['nvalue']==0) $status='Open';
							elseif ($message['nvalue']==1) $status='Closed';
						} else {
							if ($message['nvalue']==0) $status='Closed';
							elseif ($message['nvalue']==1) $status='Open';
						}
					} else {
						if ($message['nvalue']==0) $status='Off';
						elseif ($message['nvalue']==1) $status='On';
					}
					lg(' (MQTT) Switch '.$device.' => '.$status);
					store($device, $status, ' (MQTT) Switch <> ');
				} elseif ($message['dtype']=='Lighting 2') {
					if ($message['nvalue']==0) $status='Off';
					elseif ($message['nvalue']==1) $status='On';
					lg(' (MQTT) Lighting 2 '.$device.' => '.$status);
					store($device, $status, ' (MQTT) Switch ');
				} elseif ($message['dtype']=='Temp') {
					$status=$message['svalue1'];
					lg(' (MQTT) Temp '.$device.' => '.$status);	
					store($device, $status,' (MQTT) Temp ');
				} elseif ($message['dtype']=='General') {
					if ($message['stype']=='kWh') {
						$status=$message['svalue1'];
						lg(' (MQTT) kWh '.$device.' => '.$status);	
						store($device, $status,' (MQTT) kWh ');
					}
				} elseif ($message['dtype']=='Usage') {
					$status=$message['svalue1'];
					lg(' (MQTT) Usage '.$device.' => '.$status);	
					store($device, $status,' (MQTT) Usage ');
				} elseif ($message['dtype']=='Color Switch') {
					$status=$message['nvalue'];
					lg(' (MQTT) Colorswitch '.$device.' => '.$status);	
					store($device, $status,' (MQTT) Color ');
				} else {
//					store($device, $message['nvalue']);
					lg(' (MQTT) else '.print_r($message,true));	
				}
				include '/var/www/html/secure/pass2php/'.$device.'.php';
			} elseif ($device=='buiten_hum') { // 1
				$status=$message['svalue2'];
				$temp=$message['svalue1'];
				$hum=$status+3;
				if ($hum>100) $hum=100;
				if ($status>$d['buiten_temp']['m']+1) $status=$d['buiten_temp']['m']+1;
				elseif ($status<$d['buiten_temp']['m']-1) $status=$d['buiten_temp']['m']-1;
				if($hum!=$d['buiten_temp']['m']) storemode('buiten_temp', $hum);
				if ($temp!=$d['minmaxtemp']['icon']) {
					if ($temp>$d['buiten_temp']['s']+1) $temp=$d['buiten_temp']['s']+1;
					elseif ($temp<$d['buiten_temp']['s']-1) $temp=$d['buiten_temp']['s']-1;
					storeicon('minmaxtemp', $temp);
				}
			} elseif ($device=='kamer_hum') { // 2
				$status=$message['svalue2'];
				$hum=$status+3;
				if ($status>$d['kamer_temp']['m']+1) $status=$d['kamer_temp']['m']+1;
				elseif ($status<$d['kamer_temp']['m']-1) $status=$d['kamer_temp']['m']-1;
				if ($status!=$d['kamer_temp']['m']) storemode('kamer_temp', $status);
			} elseif ($device=='alex_hum') { // 3
				$status=$message['svalue2'];
				$hum=$status+5;
				if ($status>$d['alex_temp']['m']+1) $status=$d['alex_temp']['m']+1;
				elseif ($status<$d['alex_temp']['m']-1) $status=$d['alex_temp']['m']-1;
				if ($status!=$d['alex_temp']['m']) storemode('alex_temp', $status);
			} elseif ($device=='waskamer_hum') { // 4
				$status=$message['svalue2'];
				$hum=$status+5;
				if ($status>$d['waskamer_temp']['m']+1) $status=$d['waskamer_temp']['m']+1;
				elseif ($status<$d['waskamer_temp']['m']-1) $status=$d['waskamer_temp']['m']-1;
				if ($status!=$d['waskamer_temp']['m']) storemode('waskamer_temp', $status);
			} elseif ($device=='badkamer_hum') { // 5
				$status=$message['svalue2'];
				$hum=$status+5;
				if ($status>$d['badkamer_temp']['m']+1) $status=$d['badkamer_temp']['m']+1;
				elseif ($status<$d['badkamer_temp']['m']-1) $status=$d['badkamer_temp']['m']-1;
				if ($status>100) $status=100;
				if ($status!=$d['badkamer_temp']['m']) storemode('badkamer_temp', $status);
			} elseif ($device=='living_hum') { // 6
				$status=$message['svalue2'];
				$hum=$status+5;
				if ($status>$d['living_temp']['m']+1) $status=$d['living_temp']['m']+1;
				elseif ($status<$d['living_temp']['m']-1) $status=$d['living_temp']['m']-1;
				if ($status!=$d['living_temp']['m']) storemode('living_temp', $status);
			} //else lg('no file found for '.$device);
		}
	} elseif ($topic[0]=='homeassistant') {
		if (isset($topic[3])&&$topic[3]=='state') {
			global $dbname,$dbuser,$dbpass,$user,$domoticzurl;
			$d=fetchdata();
			$dag=dag();
			$device=$topic[2];
			if (file_exists('/var/www/html/secure/pass2php/'.$device.'.php')) {
				$status=ucfirst($message);
				lg(' (MQTT HASS) Switch	'.$device.'	=> '.$status);
				include '/var/www/html/secure/pass2php/'.$device.'.php';
				//$db->query("INSERT INTO devices (n,s,t) VALUES ('$name','$status','$time') ON DUPLICATE KEY UPDATE s='$status',t='$time';");
			} //else lg('no file found for '.$device.' '.print_r($topic, true).'	'.print_r($message,true));
		} //else lg(print_r($topic, true).'	'.print_r($message,true));
	} //else lg(print_r($topic, true).'	'.print_r($message,true));
}, MqttClient::QOS_AT_MOST_ONCE);
$client->loop(true);
$client->disconnect();`

**Comment by Namoshek** [comment]
As I've written before, globals are very dangerous and completely outdated in modern PHP. Also is actively sleeping between MQTT actions an issue because the underlying TCP connection will time out. This is nothing this library can prevent. You can maybe increase the timeouts in the `ConnectionSettings`, but whether that helps depends a lot on the MQTT broker and its settings as well.

**Comment by wivwiv** [comment]
I'm having the same problem. Both `setKeepAliveInterval(10)` and `setKeepAliveInterval(60)` subscriptions report an error after a certain period of time.

version: v1.8.0

### result
```bash
...
countt: 129
PHP Fatal error:  Uncaught PhpMqtt\Client\Exceptions\DataTransferException: [66] Transferring data over socket failed: Reading data from the socket failed. Has it been closed? in /Users/emqx/workspace/MQTT-Client-Examples/mqtt-client-PHP/vendor/php-mqtt/client/src/MqttClient.php:1213
Stack trace:
#0 /Users/emqx/workspace/MQTT-Client-Examples/mqtt-client-PHP/vendor/php-mqtt/client/src/MqttClient.php(1267): PhpMqtt\Client\MqttClient->readFromSocket(8192, true)
#1 /Users/emqx/workspace/MQTT-Client-Examples/mqtt-client-PHP/vendor/php-mqtt/client/src/MqttClient.php(676): PhpMqtt\Client\MqttClient->readAllAvailableDataFromSocket(true)
#2 /Users/emqx/workspace/MQTT-Client-Examples/mqtt-client-PHP/vendor/php-mqtt/client/src/MqttClient.php(649): PhpMqtt\Client\MqttClient->loopOnce(1691044071.4771, true)
#3 /Users/emqx/workspace/MQTT-Client-Examples/mqtt-client-PHP/pubsub_tcp.php(60): PhpMqtt\Client\MqttClient->loop(true)
#4 {main}
  thrown in /Users/emqx/workspace/MQTT-Client-Examples/mqtt-client-PHP/vendor/php-mqtt/client/src/MqttClient.php on line 1213

Fatal error: Uncaught PhpMqtt\Client\Exceptions\DataTransferException: [66] Transferring data over socket failed: Reading data from the socket failed. Has it been closed? in /Users/emqx/workspace/MQTT-Client-Examples/mqtt-client-PHP/vendor/php-mqtt/client/src/MqttClient.php:1213
Stack trace:
#0 /Users/emqx/workspace/MQTT-Client-Examples/mqtt-client-PHP/vendor/php-mqtt/client/src/MqttClient.php(1267): PhpMqtt\Client\MqttClient->readFromSocket(8192, true)
#1 /Users/emqx/workspace/MQTT-Client-Examples/mqtt-client-PHP/vendor/php-mqtt/client/src/MqttClient.php(676): PhpMqtt\Client\MqttClient->readAllAvailableDataFromSocket(true)
#2 /Users/emqx/workspace/MQTT-Client-Examples/mqtt-client-PHP/vendor/php-mqtt/client/src/MqttClient.php(649): PhpMqtt\Client\MqttClient->loopOnce(1691044071.4771, true)
#3 /Users/emqx/workspace/MQTT-Client-Examples/mqtt-client-PHP/pubsub_tcp.php(60): PhpMqtt\Client\MqttClient->loop(true)
#4 {main}
  thrown in /Users/emqx/workspace/MQTT-Client-Examples/mqtt-client-PHP/vendor/php-mqtt/client/src/MqttClient.php on line 1213
```

### code
```php
<?php

require('vendor/autoload.php');

use \PhpMqtt\Client\MqttClient;
use \PhpMqtt\Client\ConnectionSettings;

$server   = 'broker.emqx.io';
$port     = 1883;
$clientId = rand(5, 15);
$username = 'emqx_user';
$password = 'public';
$clean_session = false;
$mqtt_version = MqttClient::MQTT_3_1_1;

$connectionSettings  = (new ConnectionSettings)
  ->setUsername($username)
  ->setPassword($password)
  ->setKeepAliveInterval(10)
  // Last Will 设置
  ->setLastWillTopic('emqx/test/last-will')
  ->setLastWillMessage('client disconnect')
  ->setLastWillQualityOfService(1);


$mqtt = new MqttClient($server, $port, $clientId, $mqtt_version);

$mqtt->connect($connectionSettings, $clean_session);
printf("client connected\n");

$countt = 0;

$mqtt->subscribe('emqx/test', function ($topic, $message) {
    // printf("Received message on topic [%s]: %s\n", $topic, $message);
    global $countt;
    $countt = $countt + 1;
    printf("countt: %s\n", $countt);
}, 0);

// for ($i = 0; $i< 10; $i++) {
//   $payload = array(
//     'protocol' => 'tcp',
//     'date' => date('Y-m-d H:i:s'),
//     'url' => 'https://github.com/emqx/MQTT-Client-Examples'
//   );
//   $mqtt->publish(
//     // topic
//     'emqx/test',
//     // payload
//     json_encode($payload),
//     // qos
//     0,
//     // retain
//     true
//   );
//   printf("msg $i send\n");
//   sleep(1);
// }

$mqtt->loop(true);

```
