### ISSUE TITLE
[MqttClientService-Exception] The Certificate Authority file setting must contain the path to a regular file.

### ISSUE THREAD

**Issue by ashu5130** [php-mqtt/client#160]
I am getting the error below while connecting with the client:
> [MqttClientService-Exception] The Certificate Authority file setting must contain the path to a regular file.

My code:
```php
$connectionSettings = (new ConnectionSettings)
    ->setUseTls(true)
    ->setTlsSelfSignedAllowed(true)
    ->setTlsVerifyPeer(false)
    ->setTlsCertificateAuthorityFile("/etc/aws/AmazonCA1.pem")
    ->setTlsClientCertificateFile("/etc/aws/awsdevicecert.pem.crt")
    ->setTlsClientCertificateKeyFile("/etc/aws/awsprivate.key");

// Connect to the broker with the configured connection settings and with a clean session.
$client->connect($connectionSettings, true);
```

I did SSH into linux server and verified the file. All the cert and key files are present.

`test -f /etc/aws/AmazonCA1.pem && echo "file exists"` also returns true.

**Comment by Namoshek** [comment]
Is it a symlink and does the PHP process have the required permissions to access the file?

The combination of these two settings doesn't make sense by the way:
```php
->setTlsVerifyPeer(false)
->setTlsCertificateAuthorityFile("/etc/aws/AmazonCA1.pem")
```
If you don't want to verify the peer, you don't need to provide a CA certificate.

**Comment by ashu5130** [comment]
Any thought on this.

**Comment by Namoshek** [comment]
I'll look into it when I'm at home. I've tested the Amazon AWS IoT Core recently myself, without issues. So this most likely is an issue on your end, e.g. wrong line endings in the `AmazonCA1.pem` or something like that.

**Comment by Namoshek** [comment]
The only thing that seems odd is that the file is called `AmazonCA1.pem` while its called `AmazonRootCA1.pem` by default. It seems to be the correct file though, judging by the size of it.

However, please try the following commands to verify PHP is seeing the file correctly:
```sh
$> php -r "var_dump(is_file('/etc/aws/AmazonCA1.pem'));"
$> php -r "var_dump(is_readable('/etc/aws/AmazonCA1.pem'));"
$> php -r "var_dump(file_get_contents('/etc/aws/AmazonCA1.pem'));"
```
The output should be:
```
bool(true)
bool(true)
string(1188) "-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw
IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6
VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L
93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm
jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA
A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI
U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs
N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv
o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU
5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy
rqXRfboQnoZsG4q5WTP468SQvvG5
-----END CERTIFICATE-----
"
```

**Comment by ashu5130** [comment]
![image](https://github.com/php-mqtt/client/assets/11695203/b63355e9-46ff-4802-92ae-f03a7e9d3e9c)

php version is 7.4.30

**Comment by ashu5130** [comment]
We did some troubleshooting and also restarted the apache server. Now the error changed and we are getting the error below while connecting to mqtt client.

`[MqttClientService-Exception] [1000] Establishing a connection to the MQTT broker failed: Socket error [110]: Connection timed out`

**Comment by Namoshek** [comment]
Sounds like the same issue you faced last month. So it's either a misconfiguration of the AWS security policy, invalid credentials or a firewall issue.

**Comment by ashu5130** [comment]
Right, So Firewall is blocking the request. As AWS IOT endpoint IP keeps changing, I was told to use the port 443. After using 443, I am getting the exception below:
`"[1] Establishing a connection to the MQTT broker failed: A connection could not be established. Expected connect acknowledgement; received a different response else."`

**Comment by Namoshek** [comment]
Port 443 is most likely for MQTT via WebSockets, which this library does not support. This library only supports the MQTT/TCP protocol, with or without TLS.

But why should port 443 change anything in regards to the firewall rules and changing ip addresses? The host - which is what maps to the IP - is the same, even with another port.

**Comment by ashu5130** [comment]
In our system Firewall rules, Port 443 is configured to allow all the incoming IPs. While 8883 is configured to allow only fixed range of IPs.
