### ISSUE TITLE
Looking for ALPN TLS support to connect to AWS IoT 

### ISSUE THREAD

**Issue by jonofe** [php-mqtt/client#180]
Hi Guys,
I'm looking for a MQTT PHP library, which supports APLN (Application Protocol Layer Negotiation) to connect to AWS IoT MQTT service on Port 443.
Does this client support ALPN TLS?
If not, could that be added?
Thanks in advance for a short feedback.
Regards
André

**Comment by Namoshek** [comment]
If I'm correct, APLN is an HTTP feature which implies that WebSockets are the indended communication channel in your case. If that's the case, the answer is no and this is not something I'm planning to implement. At least not myself, I'm always open to contributions though. However, I'm not sure how feasible and easy it would be to implement a second, WebSocket based MQTT client in PHP to begin with. Last time I was looking for a proper implementation wasn't really fruitful.

**Comment by jonofe** [comment]
As far as I understand it does not imply WebSockets. It's MQTT over a TLS connection on port 443. 
So for example using the mosquitto_sub cli tool, I'm able to connect with the following command:

mosquitto_sub -k 45 -d -c -v -h $mqtt_host -p 443 **--tls-alpn mqtt** --cafile ./cacert.pem  -i $mqtt_client -u $mqtt_user -q 1 -t <mytopic>

Only the option --tls-alpn mqtt makes the difference.

**Comment by Namoshek** [comment]
Maybe worth a look and yeah, that's where it should go in this case. I won't be able to work on this before the weekend though and I'm not sure I've the necessary setup to even test this. A PR would be appreciated.

But anyway, do you really need to use port 443? I've tested AWS IoT before with this library (see closed issues) and I don't think I had to work around this issue.

**Comment by jonofe** [comment]
I will have a look, but I'm not sure I have the necessary programming skills to solve it. :) Will let you know...

Background of my question is the usage of the unofficial Worx Landroid API in a PHP home automation project. 
Home automation systems like FHEM, ioBroker and Home Assistant have already implemented it, but all of them documented, that it only works with TLS ALPN support. So probably in that specific case, the only option. 

But in general you are right, there are different connectivity options to AWS IoT Core service. I tried already port 8883 without TLS-ALPN and couldn't get it to work.

**Comment by jonofe** [comment]
Wasn't so complex as I initally thought. :)
Just created a pull request, which I was able to test against AWS IoT Core on TLS encrypted port 443.

**Comment by Namoshek** [comment]
PR is merged and released. Thanks for this addition!

**Comment by christoph-kluge** [comment]
Just adding a comment for those who might stumble around this issue when searching for AWS IoT. 

AWS IoT via 443 + ALPN must use `x-amzn-mqtt-ca` as alpn as described here: https://docs.aws.amazon.com/iot/latest/developerguide/protocols.html

```php
->setTlsAlpn('x-amzn-mqtt-ca')
```
