### ISSUE TITLE
Add support for `registerDisconnectedEventHandler()`

### ISSUE THREAD

**Issue by christoph-kluge** [php-mqtt/client#188]
I'm currently searching for a way to automatically perform some tasks whenever the connection is interrupted/disconnected. 

Any need for such a feature?

```php
$mqtt->registerConnectedEventHandler(function () {
    // Create temporary files
});
$mqtt->registerDisconnectEventHandler(function () {
    // Remove temporary files
});
```

**Comment by Namoshek** [comment]
Unfortunately, that's not really possible in PHP - at least not from user-land code. The client can only determine its connection state based on observation, not by passive listening. Whatever an implementation would look like, I guarantee it would not work in all cases (especially not in erroneous disconnect scenarios where you would need it most).

A listener for clean disconnects would be possible, but in my experience the broker almost never initiates the disconnect cleanly.
