### ISSUE TITLE
Fix: Update Required for PHP 8.4 Compatibility

### ISSUE THREAD

**Issue by StevenFV** [php-mqtt/client#191]
Hi,

I wanted to address the recent deprecation notice concerning implicitly nullable parameter declarations in PHP 8.4. To comply with the new standards, the codebase need to update to use explicit nullable types. For instance, where it previously declared `function test(string $test = null) {}`, it should now declare `function test(?string $test = null) {}`.

If you wish, I can contribute to your project by making the necessary adjustments.

Best regards,

Steven Francoeur-Veillet

**Comment by Namoshek** [comment]
Good catch! Feel free to send in a PR.
