### ISSUE TITLE
Would it be possible to add a Examples folder?

### ISSUE THREAD

**Issue by marcelhcb** [php-mqtt/client#26]
I know there is another repo with examples (https://github.com/php-mqtt/client-examples).
They don't seem to include examples for secure connections with encryption. Does the library allow them? Can an example be added?

**Comment by thg2k** [comment]
They are on a separate repository:

https://github.com/php-mqtt/client-examples

But I agree that they should be in the main one.

**Comment by marcelhcb** [comment]
Those examples are quite useful indeed. Thanks.
Anyway, if some more detailed example could be added with TLS suport it would be great.
I close the issue.

**Comment by Namoshek** [comment]
I agree with you that we need some more examples, and I will provide some together with the next major version. For the meantime, I added some more examples and info to the README in #27. Please let me know if that helps.

@marcelhcb TLS support will be improved in an upcoming version very soon (see #24 for more details). So you might just wait for that to be released.

**Comment by marcelhcb** [comment]
For now it's enough, thanks!
We are in preproduction still, so TLS is not an issue for now, but it will be for sure. Hence, TLS is a really important improvement. I'll be tuned!!!

**Comment by Namoshek** [comment]
@marcelhcb I released `v0.2.0` with the additional TLS options.

**Comment by marcelhcb** [comment]
I'll give it a try. Thanks.
