### ISSUE TITLE
Protocol separation in separate project and client rename to php-mqtt-client

### ISSUE THREAD

**Issue by thg2k** [php-mqtt/client#39]
I would like to submit the idea of a full protocol separation and a renaming of the client, these are two different issues but I would like to discuss them together even if they can be implemented indipendently.

**Question 1**

I propose to rename the project 'client' to 'php-mqtt-client', mainly due to the fact that when it is in the 'php-mqtt' organization it kind of makes sense, but once forked it is very annoying to have a random "client" in your workspace.

**Question 2**

I would like to experiment more on the full protocol separation, and have a new project 'php-mqtt-protocol' inside php-mqtt where you can make me maintainer. I have a fully working implementation ready to test. The idea is that starting from the "MessageProcessor" it would all belong to this separate package and it would be in the composer requires. The two project can have indipendent life and versioning.

The reason is that MQTT v5.0 is a bit complex and will require some extra work so having them separate would benefit the organization and discussion. The role of this project would be only converting the binary "on-the-wire" protocol to a logical representation, fully abstracting the version by providing feature-testing methods.

**Comment by Namoshek** [comment]
Closing this for now.
