### ISSUE TITLE
Linux use

### ISSUE THREAD

**Issue by NicklasPetersen** [php-mqtt/client#42]
I am trying to use your library on a raspberry pi.  The pi are running Debian Stretch. I have installed a mosquitto broker on the pi as well. 
I have problems with connecting My webapplication cannot connect to the broker. Are the problems with using the library on linux, or am I using the library wrong?

I have a Mqtt-config.php
```php
<?php

class MQTT_Config
{
    protected $host       = '192.168.29.56';
    protected $port       = 1883;
    protected $password   = 'password';
    protected $username   = 'mqtt';
    protected $clientId   = 'phpMQTT-publisher';
}
```

and a mqttconn.php
```php
<?php

require_once "mqtt_config.php";

/**
 * Use: For not having to write \PhpMqtt\... when defining objects
 */
use \PhpMqtt\Client\MQTTClient;
use \PhpMqtt\Client\ConnectionSettings;

/**
 * This is a class for MQTT connection
 */
class MQTTConn extends MQTT_Config
{
    public $conn;

    public function __construct()
    {
        /*try {*/
            $this->conn = new MQTTClient($this->host, $this->port, $this->clientId);

            $connectionSettings = new ConnectionSettings();
            $this->conn->connect($this->username, $this->password, $connectionSettings, true);
        /*} catch (MQTTClientException $e) {
            echo "Error: " . $e->getMessage();
        }*/
     }

     public function __destruct() {
        $this->conn->close();
     }
}
```

Just as additional information, I have been using the library with use of XAMPP on windows with no problems. However publishing takes very long time (Sometimes reaching timeout).

**Comment by Namoshek** [comment]
I'm not aware of any issues with Debian or RPis. Have you tried a public broker to cross out issues with your deployment (firewall and so)?

**Comment by thg2k** [comment]
> Just as additional information, I have been using the library with use of XAMPP on windows with no problems. However publishing takes very long time (Sometimes reaching timeout).

What version are you using? On pre 0.2.1 versions there is a bug with QoS that causes the message queue to hang. Make sure to upgrade and try again.

**Comment by NicklasPetersen** [comment]
When using the webapplication from XAMPP I still can publish to the broker. Using the exact same code, I am not able to publish anything to the broker. 
Furthermore, I have tried writing 
`mosquitto_pub -h 192.168.29.56 -t "topic" -m "message"`
This command can also publish to the broker.

**Comment by Namoshek** [comment]
Can you give a bit more information about your environment (PHP version and enabled extensions) as well as the version of the library you are using? Also logging output with debug level would be a great help in assisting you. If you need a logger implementation, you can refer to the [example repository](https://github.com/php-mqtt/client-examples/blob/master/SimpleLogger.php).

**Comment by NicklasPetersen** [comment]
I am using php-mqtt "version": "v0.2.1". 
I am using php version 7.0 with the following extensions:

[php.txt](https://github.com/php-mqtt/client/files/5465254/php.txt)

The device on 192.168.29.56 is the RPI with the broker. I do not think it is possible to use localhost, because I have another device in the same local network (192.168.29.103) that needs access to the broker. This device runs Windows CE and have access to the broker.

**Comment by Namoshek** [comment]
The library requires PHP 7.2, so I would suggest you update your PHP version and try again (I recommend going for PHP 7.4 if you are already on it). Some of the features we used (nullable type-hints for example) are not supported by PHP 7.0.

You presented your `php.ini` by the way, which does not necessarily include all enabled extensions. More useful would be the output of `php -m` which lists all extensions and zend extensions.

**Comment by NicklasPetersen** [comment]
I have undated php to 7.4 when the following 

> bcmath
bz2
calendar
Core
ctype
date
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache


I seems to be working. 
Thank you

**Comment by Namoshek** [comment]
No problem. I guess you encountered this issue because you copied your project with all dependencies from the local environment directly to your RPi. If you omit the `vendor` directory when copying and install the dependencies on the RPi directly with `composer install`, you will receive a (useful) error if your PHP version is too low. This is also the suggested way to install pretty much any PHP software.
