### ISSUE TITLE
Receiving only one message with subscribe and interrupt if max delay is reached

### ISSUE THREAD

**Issue by ZeProf2Code** [php-mqtt/client#43]
Hello!
I need to publish a message to `/in` and receive it in `/out`.
I tried this:
```php
	$mqtt = new MQTTClient('mqtt.mydomain.com', 1883, uniqid());
        $mqtt->connect('MyUsername', 'MyPassword');
        $response = null;
	$mqtt->subscribe($peripheral->hostname . '/out', function (string $topic, string $message) {
            $response = json_decode($message['message'], true);
            $mqtt->interrupt();
        });
        $mqtt->publish($peripheral->hostname . '/in', '$');
        sleep(2000);
        $mqtt->interrupt();
	$mqtt->close();
```
But it seems I'm doing something wrong. Can you help me?
Thanks!

**Comment by Namoshek** [comment]
Not sure I understand. Are you trying to write a script which receives a message on `/in` and forwards it to `/out`?
Because what you wrote, publishing something on `/in` and expecting to receive it on `/out`, is not how MQTT works. Its like calling telephone number A and expecting someone with telephone number B to receive the call. It's just not going to happen.

**Comment by ZeProf2Code** [comment]
No, I want to send a command to `/in` and receive the response in `/out`, I can't change how it works and I did it with another PHP MQTT Library but I would like to change to this one cause it's more up-to-date.

`$peripheral->hostname` is a unique identifier for a service which isn't null, the request is sent correctly.

**Comment by Namoshek** [comment]
Ok, got it. I think your only mistake is not calling `$mqtt->loop()` after you publish your message:
```php
$mqtt->subscribe($peripheral->hostname . '/out', function (string $topic, string $message) {
    $response = json_decode($message['message'], true);

    // Escape the $mqtt->loop() by setting an exit flag which is picked up on the next iteration.
    $mqtt->interrupt();
});

$mqtt->publish($peripheral->hostname . '/in', '$');

// Wait for messages on subscribed topics until $mqtt->interrupt() is called.
$mqtt->loop();

// Close the connection to the MQTT broker.
$mqtt->close();
```

**Comment by ZeProf2Code** [comment]
Yeah but if no message is received (the peripheral is offline), it will hang forever, isn't it?

**Comment by Namoshek** [comment]
Yes, the loop runs until you terminate it (however this happens). If you want to set a timeout of, let's say, 10 seconds, you have at least the following two options:

**1) Use `pcntl_signal` with `pcntl_alarm` (requires `ext-pcntl`):**
```php
// Register a signal handler for the SIGALRM signal, which indicates a timeout.
pcntl_signal(SIGALRM, function () use ($mqtt) {
    $mqtt->interrupt();
});

// Register an alarm to be sent after 10 seconds.
pcntl_alarm(10);

// ... subscribe, publish, loop and close here ...
```

**2) Use a loop event handler:**
```php
// Register a hook which is called once per loop and which interrupts the loop after some time.
$mqtt->registerLoopEventHandler(function (MqttClient $mqtt, float $elapsedTime) {
    if ($elapsedTime >= 10) {
        $mqtt->interrupt();
    }
});

// ... subscribe, publish, loop and close here ...
```

You should also check out how the hook callback is called:
https://github.com/php-mqtt/client/blob/00f8ffbe4693c6b4d418a0d1a9307420e5571d10/src/MQTTClient.php#L779-L793

The important bit is that the loop will run once more after you interrupt it in the loop event handler.

**Comment by ZeProf2Code** [comment]
Okay, thank you for your precious help!

**Comment by ZeProf2Code** [comment]
Even if I send a message myself with an MQTT Client, subscribing doesn't seems to work:
```php
		$mqtt = new MQTTClient('mqtt.mydomain.fr', 1883, uniqid());
        $mqtt->connect('MyUsername', 'MyPassword');
        $response = null;

		/**$mqtt->registerLoopEventHandler(function (MqttClient $mqtt, float $elapsedTime) {
		    if ($elapsedTime >= 5) {
		        $mqtt->interrupt();
		    }
		});**/

        $mqtt->subscribe('hello', function (string $topic, string $message) use ($response) {
            return 'hey';
            $response = json_decode($message, true);

            // Escape the $mqtt->loop() by setting an exit flag which is picked up on the next iteration.
            $mqtt->interrupt();
        });

        $mqtt->publish('hello', '$');

        // Wait for messages on subscribed topics until $mqtt->interrupt() is called.
        $mqtt->loop(true);

        // Close the connection to the MQTT broker.
	    $mqtt->close();
```

**Comment by Namoshek** [comment]
I cannot reproduce your issue. It might be an issue with your broker (it probably does not send messages back to the client which published it in the first place, even if subscribed).

The following is a minimal example which does exactly what you described. It can be run within the [`php-mqtt/client-examples` repository](https://github.com/php-mqtt/client-examples) for example (after installing composer dependencies). Although it really only needs `php-mqtt/client` as dependency installed in the `vendor` directory.

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpMqtt\Client\MQTTClient;

try {
    $mqtt = new MQTTClient("test.mosquitto.org", 1883, uniqid());
    $mqtt->connect();
    
    $mqtt->subscribe('php-mqtt/client/test', function ($topic, $message) use ($mqtt) {
        echo sprintf("Received message on topic [%s]: %s\n", $topic, $message);

        $mqtt->interrupt();
    }, MQTTClient::QOS_AT_MOST_ONCE);

    $mqtt->publish("php-mqtt/client/test", 'This is only a test message.', MQTTClient::QOS_AT_MOST_ONCE);
    
    $mqtt->loop();
    $mqtt->close();
} catch (\Throwable $e) {
    echo 'An exception occured: ' . $e->getMessage() . PHP_EOL;
}
```

**Comment by Namoshek** [comment]
Closed due to inactivity. Issue seems resolved.
