### ISSUE TITLE
Install without composer in windows wampp

### ISSUE THREAD

**Issue by hamboy75** [php-mqtt/client#45]
Hi

I have been trying to use the library without composer, and  i got different problems

Fatal error: Trait 'Concerns\OffersHooks' not found in C:\wamp64\www\Mosquito-client-0.3\client-0.3\src\MQTTClient.php on line 26

I use this code

```php
<?php

require "./PhpMqtt/Client/MQTTClient.php";

$server   = 'some-broker.example.com';
$port     = 1883;
$clientId = 'test-publisher';

$mqtt = new \PhpMqtt\Client\MQTTClient($server, $port, $clientId);
$mqtt->connect();
$mqtt->publish('php-mqtt/client/test', 'Hello World!', 0);
$mqtt->close();
```

I have all files inside PhpMqtt/Client folders in php root dir, and my php is also in php root

**Comment by Namoshek** [comment]
The answer is not what you want to hear, but you should really use composer. It is no black magic, but actually quite simple. And it takes away a lot of work of you as well.

---

If you really insist on doing it wrong (yes, it really is wrong to include a library this way!), you'll have to include all files within the `src` directory (and sub-directories) manually:
```php
require __DIR__.'/PhpMqtt/Client/MQTTClient.php';
require __DIR__.'/PhpMqtt/Client/ConnectionSettings.php';
require __DIR__.'/PhpMqtt/Client/PublishedMessage.php';
// ... and so on ...
```

**Comment by hamboy75** [comment]
ok, finally i'm using raspberry pi 4 as server. I will try there. thanks.

**Comment by jonasphp** [comment]
Just include all files like this:

$dir = __DIR__ . '/src';

// Scan the src directory for files
$files = scandir($dir);

// Loop through the files
foreach ($files as $file) {
    if (substr($file, 0, 1) === '.') {
        continue;
    }

    // Include the file if it is a PHP file
    if (substr($file, -4) === '.php') {
        require $dir . '/' . $file;
    }
}
