### ISSUE TITLE
How do I add listeners dynamically

### ISSUE THREAD

**Issue by wuxian12** [php-mqtt/client#48]
After an MQTT connection is started, how can we add a new topic listener?

Take this client for example:
```php
$clientId = 'test-subscriber-aa';
$server   = '192.168.0.51';
$port     = 1883;

$mqtt = new \PhpMqtt\Client\MQTTClient($server, $port, $clientId);

$mqtt->connect();

$mqtt->subscribe('php-mqtt/client/aa', function ($topic, $message) {
    echo sprintf("Received message on topic [%s]: %s\n", $topic, $message);
}, 0);

$mqtt->loop(true);
```

How can I add a new topic after running `$mqtt->loop(true)`, which blocks the whole application?

**Comment by Namoshek** [comment]
There is a few ways you can accomplish this. To decide on the right option, it is important to also consider how the process learns about new users (how is this information given to the executing thread?).

Just a quick summary of some options I know of:

1. **Wrap `$client->loop()` with your own loop:**
  This may sound weird and probably harder than it is. But the idea is simple. You build your own loop which somehow retrieves new logged in users and uses this information to send subscribe requests. Then, also within the loop, you call the MQTT client loop with a defined exit condition. To achieve this, you have two more options in my opinion:
      
      1. You can either use the second parameter of `$client->loop(bool $allowSleep = true, bool $exitWhenQueuesEmpty = false, int $queueWaitLimit = null)` to exit the loop regularly, as soon as all queues are empty (which, depending on your type of application, can be reliable or not so reliable in terms of regularity).

      2. You can use `$client->interrupt()` within a _loop event handler_ which you can register using the following method:
        https://github.com/php-mqtt/client/blob/6d68c8124759e5b92284e3654aa4e5402c9b99bd/src/Concerns/OffersHooks.php#L33-L53
          The idea is to interrupt the client as soon as the event handler is called, which will make it exit the loop during the next iteration (it basically completes one iteration and then exits):
          ```php
          $clientId = 'test-subscriber-aa';
          $server   = '192.168.0.51';
          $port     = 1883;
          
          $mqtt = new \PhpMqtt\Client\MQTTClient($server, $port, $clientId);
          
          $mqtt->connect();
          
          $mqtt->subscribe('php-mqtt/client/aa', function ($topic, $message) {
              echo sprintf("Received message on topic [%s]: %s\n", $topic, $message);
          }, 0);
          
          $mqtt->registerLoopEventHandler(fn ($client) => $client->interrupt());

          while (true) {
              $newUsers = []; // retrieve new users here
              foreach ($newUsers as $newUser) {
                  $mqtt->subscribe('some/topic/'.$newUser, $mySubscriberCallback);
              }

              $mqtt->loop(true); // only retrieves all data from the receive buffer, then exits
          }
          ```

2. **Use an _event loop handler_ as described above to subscribe to new topics:**
    ```php
    $clientId = 'test-subscriber-aa';
    $server   = '192.168.0.51';
    $port     = 1883;
    
    $mqtt = new \PhpMqtt\Client\MQTTClient($server, $port, $clientId);
    
    $mqtt->connect();
    
    $mqtt->subscribe('php-mqtt/client/aa', function ($topic, $message) {
        echo sprintf("Received message on topic [%s]: %s\n", $topic, $message);
    }, 0);
    
    $mqtt->registerLoopEventHandler(function ($client) {
        $newUsers = []; // retrieve new users here
        foreach ($newUsers as $newUser) {
            $client->subscribe('some/topic/'.$newUser, $mySubscriberCallback);
        }
    });
    
    $mqtt->loop(true);
    ```

**Comment by wuxian12** [comment]
$mqtt->loop(true); After that, the process will block and not be able to do anything else. How do you trigger the registerLoopEventHandler method

**Comment by Namoshek** [comment]
You need to register the loop handler before calling `$mqtt->loop()` as shown in the examples above. The callback you register is called by the `loop()` method internally. It basically lets you inject code into the loop.

**Comment by wuxian12** [comment]
thank you

**Comment by Namoshek** [comment]
I recommend having a look at the client code itself, especially the `loop()` method. It really is worth knowing about:
https://github.com/php-mqtt/client/blob/6d68c8124759e5b92284e3654aa4e5402c9b99bd/src/MQTTClient.php#L766-L924
