### ISSUE TITLE
TypeError: chr() expects parameter 1 to be int, string given

### ISSUE THREAD

**Issue by sten** [php-mqtt/client#6]
I get an error on connection in the `performConnectionHandshake` function on line 235:
TypeError: chr() expects parameter 1 to be int, string given 

When I run a debugger I can see that the value of `$i` passed to `chr()` is a string. I assume this is caused by using `.=` instead of `+=` on line 226 and 231. If I replace this in the code, everything works.

I am using PHP 7.4.2.

**Comment by sten** [comment]
@Namoshek Thanks a lot! Works like a charm!

**Comment by Namoshek** [comment]
Awesome! Obviously, I never tested the authentication... good to know it works!
