### ISSUE TITLE
Client is disconnecting?

### ISSUE THREAD

**Issue by Afrowson** [php-mqtt/client#65]
I updated from 0.3 to 1.0 

since then the client seems to disconnect after a short time, or the server is disconnec ting the client...
my Server is a " mosquitto version 1.6.12 "

0.3 working code:

```php
$mqtt = new \PhpMqtt\Client\MQTTClient($server, $port, $clientId,null,null,\logger());
$connectionSettings = new \PhpMqtt\Client\ConnectionSettings(
    1, false, false, 5, 10, 10, null, null, false, false, false
);
$mqtt->connect(null, null, $connectionSettings, true);
$topic = "ZKS/#";
$mqtt->subscribe($topic, function ($topic, $message) {
    dump("Received message on topic [%s]: %s\n", $topic, $message);
}, 0);
$mqtt->loop(true);
```

1.0 broken code:

```php
$protocolVersion = MqttClient::MQTT_3_1;
$mqtt = new MqttClient($server, $port, $clientId, $protocolVersion, null, \logger());

$connectionSettings = (new ConnectionSettings())
    ->setSocketTimeout(10)
    ->setKeepAliveInterval(5)
    ->setLastWillQualityOfService(1)
    ->setUseTls(false);

$mqtt->connect($connectionSettings, true);
$topic = "ZKS/#";
$mqtt->subscribe($topic, function ($topic, $message) {
    dump("Received message on topic [%s]: %s\n", $topic, $message);
}, 0);
$mqtt->loop(false);
```

> Exception:
>   PhpMqtt\\Client\\Exceptions\\DataTransferException(code: 66): [66] Transferring data over socket failed: Reading data from the socket failed. Has it been closed?
>
> Stacktrace:
>  #0 ...vendor/php-mqtt/client/src/MqttClient.php(1113): PhpMqtt\\Client\\MqttClient->readFromSocket(8192, true)
>  #1 ...vendor/php-mqtt/client/src/MqttClient.php(586): PhpMqtt\\Client\\MqttClient->readAllAvailableDataFromSocket()
>  #2 ...app/Console/Commands/ZKSListenCommand.php(47): PhpMqtt\\Client\\MqttClient->loop(false) 

In both cases the client is recieving all the available messags correct on connection but in 1.0 it gets disconnected quickly after the connection has been made.

For production in would enable tls that is why the ConnectionSettings exists. removing it doesnt change anything.

The client is recieving empty messags for some time, untill the socket is closed. I dumped severaly things on Line:1055ff 

I don`t understand the problem, maybe someone can help?

**Comment by Namoshek** [comment]
Did you have a look at the logs of your broker to see if there is a useful hint about the disconnect? And are you potentially reusing the same `$clientId` twice (concurrently)?

**Comment by Namoshek** [comment]
Hm, interesting. I'll give this a try in the evening. Not sure what could cause this.

**Comment by Afrowson** [comment]
New Version:
mqtt    | 1611157105: New connection from 172.20.201.50 on port 1883.
mqtt    | 1611157105: New client connected from 172.20.201.50 as test-subscriber (p1, c1, k5).
mqtt    | 1611157105: No will message specified.
mqtt    | 1611157105: Sending CONNACK to test-subscriber (0, 0)
mqtt    | 1611157105: Received SUBSCRIBE from test-subscriber
mqtt    | 1611157105: 	ZKS/# (QoS 0)
mqtt    | 1611157105: test-subscriber 0 ZKS/#
mqtt    | 1611157105: Sending SUBACK to test-subscriber
mqtt    | 1611157105: Sending PUBLISH to test-subscriber (d0, q0, r1, m0, 'ZKS/G8Z3', ... (409 bytes))
mqtt    | 1611157105: Sending PUBLISH to test-subscriber (d0, q0, r1, m0, 'ZKS/ZKS_Server', ... (141 bytes))
mqtt    | 1611157105: Sending PUBLISH to test-subscriber (d0, q0, r1, m0, 'ZKS/', ... (230 bytes))
mqtt    | 1611157112: Client test-subscriber has exceeded timeout, disconnecting.

Old version:
mqtt    | 1611156961: New connection from 172.20.201.50 on port 1883.
mqtt    | 1611156961: New client connected from 172.20.201.50 as test-subscriber (p1, c1, k10).
mqtt    | 1611156961: No will message specified.
mqtt    | 1611156961: Sending CONNACK to test-subscriber (0, 0)
mqtt    | 1611156962: Received SUBSCRIBE from test-subscriber
mqtt    | 1611156962: 	ZKS/# (QoS 0)
mqtt    | 1611156962: test-subscriber 0 ZKS/#
mqtt    | 1611156962: Sending SUBACK to test-subscriber
mqtt    | 1611156962: Sending PUBLISH to test-subscriber (d0, q0, r1, m0, 'ZKS/G8Z3', ... (409 bytes))
mqtt    | 1611156962: Sending PUBLISH to test-subscriber (d0, q0, r1, m0, 'ZKS/ZKS_Server', ... (141 bytes))
mqtt    | 1611156962: Sending PUBLISH to test-subscriber (d0, q0, r1, m0, 'ZKS/', ... (230 bytes))
mqtt    | 1611156971: Received PINGREQ from test-subscriber
mqtt    | 1611156971: Sending PINGRESP to test-subscriber
mqtt    | 1611156982: Received PINGREQ from test-subscriber
mqtt    | 1611156982: Sending PINGRESP to test-subscriber
mqtt    | 1611156992: Received PINGREQ from test-subscriber
mqtt    | 1611156992: Sending PINGRESP to test-subscriber
mqtt    | 1611157002: Received PINGREQ from test-subscriber
mqtt    | 1611157002: Sending PINGRESP to test-subscriber
mqtt    | 1611157012: Received PINGREQ from test-subscriber
mqtt    | 1611157012: Sending PINGRESP to test-subscriber
mqtt    | 1611157022: Received PINGREQ from test-subscriber
mqtt    | 1611157022: Sending PINGRESP to test-subscriber
mqtt    | 1611157032: Received PINGREQ from test-subscriber
mqtt    | 1611157032: Sending PINGRESP to test-subscriber
mqtt    | 1611157042: Received PINGREQ from test-subscriber
mqtt    | 1611157042: Sending PINGRESP to test-subscriber
mqtt    | 1611157042: Socket error on client test-subscriber, disconnecting.

It seems like the new Version isn`t sending a ping?

**Comment by Afrowson** [comment]
lowering the KeepAliveInterval config to 5 didnt help. 

maybe i am using the new settings wrong?  have fon debugging. if you need anything, i am willing to help.

**Comment by Namoshek** [comment]
That's somewhat helpful, but I'll need to check it out myself later when I'm home. It's hard to debug from logs only. 👍 

The logic hasn't really changed from `v0.3` though.

**Comment by Namoshek** [comment]
**Trying to reproduce your issue:**
Using a common test setup for the MQTT client, I created some test certificates and started a Mosquitto broker with the version you described (from within the `client` repository):
```sh
sh create-certificates.sh
docker run --rm -it -p 1883:1883 -p 8883:8883 -p 8884:8884 -v $(pwd)/.ci/tls:/mosquitto-certs -v $(pwd)/.ci/mosquitto.conf:/mosquitto/config/mosquitto.conf eclipse-mosquitto:1.6.12
```
I then used your exact code with the `SimpleLogger` from the [`client-examples`](https://github.com/php-mqtt/client-examples) repository. But even after about ten test runs with different amounts and sizes of published messages, I never had a connection timeout in the logs like you did.

**Next steps:**
First, can you try if changing
https://github.com/php-mqtt/client/blob/ca47fff0d5513c7ebeba8698e8ff8397414c38d4/src/MqttClient.php#L602-L604
to
```php
if (($this->nextPingAt() - 0.5) <= microtime(true)) {
    $this->ping();
}
```
solves your issue?

If this doesn't help, I need a bit more information from you. The following is what comes to my mind right now, but if you have more details, feel free to share them as well:
- Used PHP version
- What type of connection is used between the broker and your script? Is the broker on localhost or on another host? Are you connecting using fiber or a mobile network?
- If the broker is not on localhost, can you provide a ping output (with redacted IP)? I'm interested in the latency.
- What is a typical message size of yours and how many messages per second are we talking about?

**Comment by Afrowson** [comment]
* php version is 7.4
* It is a server through a VPN
* I connect via fiber
* Ping output:
     round-trip min/avg/max/stddev = 5.801/15.784/101.510/21.670 ms
     64 bytes from XXXXXXX: icmp_seq=5 ttl=64 time=14.105 ms
* Message Sizes are between ~100 and ~500 bytes

Doing the suggested edit did not help. 

I restarted the Brooker on the remote server, now both Clients work and that even with setKeepAliveInterval(10)... 🤷‍♂️

So my problem seems to be resolved. if something comes up or if i understand what it was, i will come back to you.
