### ISSUE TITLE
What is a best way to suscriber using Laravel o Symfony?

### ISSUE THREAD

**Issue by ssheduardo** [php-mqtt/client#67]
I am using Laravel and I want to subscribe to a publication, the code you have is great but I want to know what is the best way to do it.

Would it be to create a command with your code and then create a cron so that every minute it runs or leave it running all the time.
The problem is how to detect if the script fails or stops.
Any suggestions?

**Comment by Namoshek** [comment]
You would want to create a console command and ensure it keeps running using supervisor for example, similar to queue workers (consult the official Laravel documentation for an example). A cronjob makes only sense for RPC style subscriptions.

For an easier integration, I recommend using [`php-mqtt/laravel-client`](https://github.com/php-mqtt/laravel-client). It is a wrapper of this library for Laravel.

**Comment by Afrowson** [comment]
If you want to subscribe to several Topics maybe think about implementing it as a [Service](https://laravel.com/docs/8.x/providers) so you can add your default config to the Object and only need to write the connection part of your code multiple times.

**Comment by ssheduardo** [comment]
> If you want to subscribe to several Topics maybe think about implementing it as a [Service](https://laravel.com/docs/8.x/providers) so you can add your default config to the Object and only need to write the connection part of your code multiple times.

Ah well it would be nice, some example that you have on hand to study it.?

**Comment by Namoshek** [comment]
Using the mentioned Laravel wrapper for the MQTT client, you don't need a service provider or even a service. You can simply add multiple subscriptions in a row. Reducing this to even less code is pretty much impossible due to the required loop. The client configuration is abstracted away using Laravels config system.

```php
use PhpMqtt\Client\Facades\MQTT;

/** @var \PhpMqtt\Client\Contracts\MqttClient $mqtt */
$mqtt = MQTT::connection();

$mqtt->subscribe('foo/+', function (string $topic, string $message) {
    echo sprintf('Received QoS level 1 message on topic [%s]: %s', $topic, $message);
}, 1);
$mqtt->subscribe('bar/+', function (string $topic, string $message) {
    echo sprintf('Received QoS level 2 message on topic [%s]: %s', $topic, $message);
}, 2);

$mqtt->loop(true);
```

**Comment by ssheduardo** [comment]
> Using the mentioned Laravel wrapper for the MQTT client, you don't need a service provider or even a service. You can simply add multiple subscriptions in a row. Reducing this to even less code is pretty much impossible due to the required loop. The client configuration is abstracted away using Laravels config system.
> 
> ```
> use PhpMqtt\Client\Facades\MQTT;
> 
> /** @var \PhpMqtt\Client\Contracts\MqttClient $mqtt */
> $mqtt = MQTT::connection();
> 
> $mqtt->subscribe('foo/+', function (string $topic, string $message) {
>     echo sprintf('Received QoS level 1 message on topic [%s]: %s', $topic, $message);
> }, 1);
> $mqtt->subscribe('bar/+', function (string $topic, string $message) {
>     echo sprintf('Received QoS level 2 message on topic [%s]: %s', $topic, $message);
> }, 2);
> 
> $mqtt->loop(true);
> ```

The package not have support to Laravel 5.7 with Php 7.3 :(
https://github.com/php-mqtt/laravel-client
I have created a ticket to see if you can enable it.

**Comment by Namoshek** [comment]
I guess this question has been answered and the issue is resolved.
