### ISSUE TITLE
Disconnect is protected method

### ISSUE THREAD

**Issue by SergioMiller** [php-mqtt/client#68]
Call to protected method PhpMqtt\Client\MQTTClient::disconnect()

**Comment by rizkyanfasafm** [comment]
What's your solving the problem?

**Comment by Namoshek** [comment]
This has been a wrong report, the method is `public` for quite some time already, especially when using `v1` of the client.
https://github.com/php-mqtt/client/blob/e3cbfcb09868d0d2ce73b2953b91c47fa0ac6876/src/MqttClient.php#L440-L453

**Comment by geri777** [comment]
@Namoshek - my IDE says "disconnect" is not defined. (Version v1.6.0)
in https://github.com/php-mqtt/client/blob/22a207edef01d5f0ed3a6a79565cc425b678d786/src/MqttClient.php 
in line 555 disconnect() is defined as protected.

**Comment by Namoshek** [comment]
@geri777 In the version you linked, `disconnect()` is on line 507 and `public`. You must be experiencing another issue.

**Comment by geri777** [comment]
Sorry Namoshek, I used an old version. Everything is correct as you said.
