### ISSUE TITLE
Cannot publish QOS = 2

### ISSUE THREAD

**Issue by brandaobrandisborges** [php-mqtt/client#69]
When trying to publish with QOS_EXACTLY_ONCE, there are no errors but the message is not published. Other QOS without any problem.

> $client->publish('foo/bar/baz', "Hello world!", MqttClient::QOS_EXACTLY_ONCE);

**Comment by Namoshek** [comment]
Please have a look at the [`php-mqtt/client-examples` repository](https://github.com/php-mqtt/client-examples), specifically the [QoS 2 Publishing example](https://github.com/php-mqtt/client-examples/blob/master/01_publishing/03_publish_with_qos_2.php). It explains how it is done.

Background:
- QoS 0 is a fire-and-forget message flow without acknowledgement from the broker's side.
- QoS 1 is an acknowledged message flow where the broker confirms receipt.
- QoS 2 is a double-acknowledged message flow where the client and the broker each confirm receipt of the message (and the acknowledgement).

For any QoS level other than 0, the client has to listen for an acknowledgement (and potentially send another one). This requires calling the `loop()` method of the client. `publish()` is non-blocking, while `loop()` is blocking.

**Comment by brandaobrandisborges** [comment]
Indeed I was trying to use QoS != 0 without the loop; I haven't checked the provided solution as I migrated to python due to other reasons. Thanks!
