### ISSUE TITLE
PHP 7.3 compatibility

### ISSUE THREAD

**Issue by Domochip** [php-mqtt/client#74]
This is more a question than an issue : 
Why PHP 7.4 is the lowest supported version? Does there is some specific code requiring 7.4?
Lot of installation, even fresh new, are done using PHP 7.3. Default version of PHP for Debian Buster is 7.3 too.

Do you think it's possible to make this library PHP 7.3 compatible?

thanks

**Comment by Namoshek** [comment]
The library is using PHP 7.4 features like type declarations for class properties. Would it be possible to back-port it to PHP 7.3? Absolutely. Will I do it? Nope, sorry.

My reasoning for this decision is that the used features of PHP 7.4 are important for the code quality and overall maintainability of the library. With PHP 8 being available for a few months now, and PHP 7.4 being available for almost one and a half years already, it is quite reasonable to expect users to use at least PHP 7.4 in my opinion.

If you really need PHP 7.3 support, feel free to create a fork. A tool like [`rectorphp/rector`](https://github.com/rectorphp/rector) can aide you in the back-port process. It is most likely only a 15-30 minute job, if you know what you are doing. But please be aware that I will not be able to provide support for such a back-port.

**Comment by Domochip** [comment]
OK, thx a lot for your answers.

**Comment by thg2k** [comment]
To be fair if you want 7.2 you could look into 0.x releases, they still work fine and should be compatible with your env. I still run that myself.

**Comment by ssheduardo** [comment]
@thg2k So you could do a fork on version 0.xx and add the improvements of the current versions with PHP 7.2 or 7.3?

**Comment by Namoshek** [comment]
That would be way more effort than back-porting the current v1. thg2k is talking about using v0.3 as is.

**Comment by s00d** [comment]
try my fork https://github.com/s00d/client

**Comment by Domochip** [comment]
thanks a lot for your offer but we built a python daemon to handle MQTT communications finally
