### ISSUE TITLE
Transfering data over socket failed: Sending data over the socket failed. Has it been closed?

### ISSUE THREAD

**Issue by radu-bethub** [php-mqtt/client#8]
Hello,

I'm getting randomly the below error:

> local.ERROR: [65] Transfering data over socket failed: Sending data over the socket failed. Has it been closed? {"exception":"[object] (PhpMqtt\\Client\\Exceptions\\DataTransferException(code: 65): [65] Transfering data over socket failed: Sending data over the socket failed. Has it been closed? at /var/www/html/vendor/php-mqtt/client/src/MQTTClient.php:1302)

I'm using mosquitto mqtt server on centos 7. both services are on the same server (php + mosquitto).

Connections settings:
```php
$settings = new ConnectionSettings(
    $qualityOfService = 1,
    $retain = false,
    $blockSocket = false,
    $socketTimeout = 30,
    $keepAlive = 10,
    $resendTimeout = 10,
    $lastWillTopic = null,
    $lastWillMessage = null
);
```
Thanks in advance.

Regards,

**Comment by Namoshek** [comment]
Hi, are you using the latest version of the package (`v0.1.4`)? And what is the role of your client, publishing or subscribing (or both)? This somehow sounds like the issue explained and tackled in #5.

**Comment by radu-bethub** [comment]
Hi, I'm using latest version v0.1.4 and the role of my client is to subscribing and listen for messages. I removed the entire vendor folder and I ran composer install just to be sure.

**Comment by Namoshek** [comment]
Are you using a logger by any chance and can give some debug output until the error occurs? You can get an example logger from the [php-mqtt/client-examples](https://github.com/php-mqtt/client-examples) project, if you are unsure how to add one.

**Comment by radu-bethub** [comment]
I will check today and I will come back.
Thanks

**Comment by radu-bethub** [comment]
`
[2020-07-15 12:02:57] [info] Connection with MQTT broker at [127.0.0.1:1883] established successfully. ([])
.[2020-07-15 12:03:17] [error] Sending data over the socket to an MQTT broker failed. ({"broker":"127.0.0.1:1883"})

   PhpMqtt\Client\Exceptions\DataTransferException  : [65] Transfering data over socket failed: Sending data over the socket failed. Has it been closed?

  at /var/www/client.cybsm.com/vendor/php-mqtt/client/src/MQTTClient.php:1302
    1298|         if ($result === false || $result !== $length) {
    1299|             $this->logger->error('Sending data over the socket to an MQTT broker failed.', [
    1300|                 'broker' => sprintf('%s:%s', $this->host, $this->port),
    1301|             ]);
  > 1302|             throw new DataTransferException(self::EXCEPTION_TX_DATA, 'Sending data over the socket failed. Has it been closed?');
    1303|         }
    1304|         
    1305|         // After writing successfully to the socket, the broker should have received a new message from us.
    1306|         // Because we only need to send a ping if no other messages are delivered, we can safely reset the ping timer.

  Exception trace:

  1   PhpMqtt\Client\MQTTClient::writeToSocket()
      /var/www/client.cybsm.com/vendor/php-mqtt/client/src/MQTTClient.php:348

  2   PhpMqtt\Client\MQTTClient::ping()
      /var/www/client.cybsm.com/vendor/php-mqtt/client/src/MQTTClient.php:667

  Please use the argument -v to see more details.
`

I just checked and I'm getting this error exactly after 20 seconds.

**Comment by codingyu** [comment]
@radu-bethub 
It may be caused by duplicate client id

**Comment by radu-bethub** [comment]
The Client Id was the issue. Thank you for your good job!

**Comment by Namoshek** [comment]
Interesting find. Can you elaborate a bit on why the client id was the issue? Did your Mosquitto not recognize the client and simply "ignore" it?

If it's an issue with the connection handshake, I'd like to reproduce and fix it. If it's something else, an explanation might be useful for future readers. Thanks it advance!

**Comment by codingyu** [comment]
> The Client Id was the issue. Thank you for your good job!

Later, I found that the logs are different, I thought I was wrong, it seems that the problem has been solved

**Comment by codingyu** [comment]
@Namoshek 
I run a subscriber client on the server.

Run the same client id again locally.

It can receive messages normally when it is turned on.

After a while (less than a minute), an exception will be thrown.

**Comment by Namoshek** [comment]
Ok, that makes somewhat sense. I don't really understand why your broker even accepts two connections with the same client id, but I'm glad you found the issue and could resolve it yourself.
