### ISSUE TITLE
Installation on Raspberry Pi

### ISSUE THREAD

**Issue by Eba-M** [php-mqtt/client#87]
I tried to install your package on my RPI.
I managed to install composer.
I run the composer and found a new directory vendor
but i missed for example:
\PhpMqtt\Client\MQTTClient
there is not such directory unter ../vendor if found
vendor/php-mqtt/client
but with no Capital Letter
at the end - i cannot load such file when i run:
$mqtt = new \PhpMqtt\Client\MqttClient($server, $port, $clientId);
$pcntl_signal(SIGINT, function (int $signal, $info) use ($mqtt) {
    $mqtt->interrupt();
});
What have i done wrong? to install the package

**Comment by Namoshek** [comment]
You should make yourself familiar with the basics of composer first ([getting started](https://getcomposer.org/doc/00-intro.md)). Directories and namespaces are independent of each other. Autoloading is what ties them both together.

In short, after installing the package, run `composer dump-autoload` to create `vendor/autoload.php`. You then include this `autoload.php` in your code on the very top:
```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpMqtt\Client\MqttClient;

$mqtt = new MqttClient('localhost', 1883);
```

Every single example in the [`php-mqtt/client-examples` repository](https://github.com/php-mqtt/client-examples) uses the same approach. The examples are also a very good starting point for customizations.

**Comment by Eba-M** [comment]
Even after more then 40 years in programming, the IoT is new to me.
Ich habe a program Rundung on my Raspi an it though it may be a good idea, to use MQTT instead of a RAMDisk to control my application via a Website with no need using ssh.
I have a test publisher running on my Raspi, it works fine with my subscriber both written with Python.

Now I checked the '/vendor/autoload.php'

There ist a reference on

require_once __DIR__ . '/composer/autoload_real.php';

There ist a directory /vendor/composer but no autoload_real.php;

my php-code stops at

require __DIR__ . '/vendor/autoload.php';

I still don’t understand how the composer works.


Best

Eberhard

**Comment by Namoshek** [comment]
Composer is actually very simple. It registers a lookup table (an array) with class names as key and the file containing the class as value. Whenever you use a class (or import it using `use Foo/Bar`, PHP will use the autoloading information of composer to include the file with the class.

Are you sure your script is in the same directory where also the `vendor` directory is situated at? If you used `composer dump-autoload` to create the `autoload.php` (and all the files it uses internally), there should be nothing else to do.

The only thing which could cause random errors is if you are not using PHP 7.4 or higher, which this library requires.

**Comment by Eba-M** [comment]
I Upgraded to php 7.4

I inserted 
require __DIR__ . ‚/home/pi/dev/vendor/autoload.php‘;
Into my script.

I can invoke that file from the command line
Php /home/pi/dev/vendor/autoload.php

But the script stops after this line

Best

Eberhard

**Comment by Eba-M** [comment]
Hallo,
I startet my Test-script direct from the command-line und got the directory-problem fixt. It always uses relative directory no absolute. But it stops at the loop with receiving no messages from the local mosquito-Broker, which I send with my Python app. (This works fine, I see the receiving msg in my app)

When I tried to request the webpage from my remote Chrom Browser on my Mac,
I get: 
Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0“.

Despite 
PHP 7.4.25 (cli) (built: Nov  1 2021 20:07:52) ( NTS )
Installed on my Raspi

Do you have any idea what may still be wrong?

Best

Eberhard

**Comment by Namoshek** [comment]
`php-cli` and `php-fpm` (which is the webserver for the browser) is not the same. You most likely updated only one of the both.

**Comment by Eba-M** [comment]
Now my app works on CLI on my Raspberry, but I fail to push the data to  my browser Chrome on my Mac. As soon the line
pcntl_async_signals(true);
Is being processed, the browser stops. I don’t know why?

Its a slow bur frustrating progress.

Best

Eberhard

**Comment by Namoshek** [comment]
Well, all the issues you are having are not related to this library at all. `ext-pcntl` is a PHP extension and most likely missing from your installation, or just not enabled. If you turn on some error reporting for your PHP script(s), you might get more helpful output.
